# FROM carlonluca/qt-dev:5.15.8-lts-lgpl
# FROM oven/bun:latest
FROM python:3.10.5-slim-buster


ENV TERM="dumb"

ARG DEFAULT_BRANCH="main"

RUN apt update && \
    apt install -y \
    python3-dev python3-distro python3-setuptools python3-pip \
    autotools-dev automake autoconf autopoint \
    libtool \
    g++ \
    make cmake pkg-config \
    bison \
    flex \
    nasm \
    libxv-dev \
    libx11-dev \
    libx11-xcb-dev \
    libpulse-dev \
    gettext \
    libxext-dev \
    libxi-dev \
    x11proto-record-dev \
    libxrender-dev \
    libgl1-mesa-dev \
    libxfixes-dev \
    libxdamage-dev \
    libxcomposite-dev \
    libasound2-dev \
    build-essential \
    gperf \
    wget \
    libxtst-dev \
    libxrandr-dev \
    libglu1-mesa-dev \
    libegl1-mesa-dev \
    git \
    xutils-dev \
    intltool \
    ccache \
    libssl-dev \
    libjson-glib-1.0-0 \
    libjson-glib-dev \
    ninja-build \
    libxml2-dev libglib2.0-dev libjson-glib-dev
    # \
    # && rm -rf /var/lib/apt/lists/* 
    
# RUN python3 -m venv /opt/venv
# # Enable venv
# ENV PATH="/opt/venv/bin:$PATH"    

RUN pip3 install meson==0.62.2 hotdoc==0.13.7 ninja tomli distro

RUN git clone -b ${DEFAULT_BRANCH} https://github.com/drunkody/cerbero.git && \
    mkdir $HOME/.cerbero && \
    echo "allow_parallel_build=True" > $HOME/.cerbero/cerbero.cbc && \
    echo "use_ccache=True" >> $HOME/.cerbero/cerbero.cbc && \
    cd cerbero && \
      echo "local_sources=\"/cerbero/cerbero-sources\"" >> /usr/src/localconf.cbc && \
      echo "home_dir=\"/cerbero/cerbero-build\"" >> /usr/src/localconf.cbc && \
      echo "# Set custom remote and branch for all gstreamer recipes" >> /usr/src/localconf.cbc && \ 
      echo "recipes_remotes = {'gstreamer-1.0': {'custom-remote': 'https://github.com/drunkody/gstreamer.git'}}" >> /usr/src/localconf.cbc && \
      echo "recipes_commits = {'gstreamer-1.0': 'custom-remote/main'}" >> /usr/src/localconf.cbc && \  
      ./cerbero-uninstalled -v rust -t -c /usr/src/localconf.cbc bootstrap -y --build-tools=no --toolchains=no

RUN cd cerbero && ./cerbero-uninstalled -v rust -t -c /usr/src/localconf.cbc -c config/cross-android-arm64.cbc bootstrap

# TODO nix-cross/howbuild.md && cp -r gcfhvdbcwp4s70wqgs4fdfb744lgl43i-libunwind-1.6.2/* /cerbero/cerbero-build/dist/android_arm64
# && cp gstreamer-1.0-android-arm64-1.22.7.tar.xz /usr/src

# RUN cd cerbero && ./cerbero-uninstalled -v rust -t -c /usr/src/localconf.cbc -c config/cross-android-arm64.cbc package gstreamer-1.0 && \
#       cd .. && \
#     rm -rf /cerbero/cerbero-build/{dist,logs,sources} && \
#     rm -f /cerbero/cerbero-build/{linux,windows,android}*.cache && \
#     dnf clean all                           
ENTRYPOINT [ "" ]