version: '3.6'

services:
  builder:
    container_name: qt-gst-builder
    build:
      context: ./.docker/5.15.8-lts-lgpl-gst-1.22.5
      dockerfile: Dockerfile
    #   network: host
    # network_mode: host
    command: tail -f /dev/null
    environment:
      - QT_GRAPHICSSYSTEM=native
    volumes:
      - .:/usr/src